name: marge_homer
channels:
  - defaults
dependencies:
  - mpi4py=3.0.3
  - mpich=3.3.2
  - pip=19.0.3
  - cython=0.29.5
  - h5py=2.9.0
  - hdf5=1.10.4
  - matplotlib=3.0.2
  - numpy=1.16.2
  - python=3.7.2
  - scikit-learn=0.20.2
  - scipy=1.2.1
  - yaml=0.1.7
  - tensorflow-gpu==1.13.1
  - keras==2.2.4
  - pip:
    - -rrequirements.txt --install-option="--no-deps"
